# Generated by Django 4.1.7 on 2024-07-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeritajeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteperitar',
            name='cuil_entrega',
            field=models.CharField(max_length=13, verbose_name='Cuil de Entrega'),
        ),
    ]
